apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: brunocercan/nginx:conf
    resources:
      limits:
        memory: "64Mi"
        cpu: "150m"
    ports:
      - containerPort: 80
