apiVersion: v1
kind: Pod
metadata:
  name: pod-clientes
  labels:
    app: pod-clientes
spec:
  containers:
  - name: pod-clientes
    image: brunocercan/api-clientes:dbk8
    ports:
      - containerPort: 5000
    envFrom:
      - configMapRef:
          name: db-configmap