apiVersion: v1
kind: Pod
metadata:
  name: api-produtos
  labels:
    name: api-produtos
spec:
  containers:
  - name: api-produtos
    image: brunocercan/api-produtos
    resources:
      limits:
        memory: "64Mi"
        cpu: "150m"
    ports:
      - containerPort: 5000
